# Generated by Django 4.2.10 on 2026-05-09 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('vitamins', models.JSONField(default=dict)),
                ('minerals', models.JSONField(default=dict)),
                ('allergens', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='food_analysis/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.JSONField(default=dict)),
                ('recognized_items', models.JSONField(default=list)),
                ('nutritional_info', models.JSONField(default=dict)),
                ('safety_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('danger', 'Danger')], default='safe', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
