# Generated by Django 4.2.10 on 2026-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanalysis',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='food_analysis/%Y/%m/%d/'),
        ),
    ]
