# Generated by Django 4.2.10 on 2026-05-09 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='medical_reports/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(default=dict)),
                ('raw_text', models.TextField(blank=True)),
                ('processing_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedHealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('description', models.TextField()),
                ('severity', models.CharField(default='moderate', max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='medical_processing.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('recommendation', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to='medical_processing.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=255)),
                ('reaction_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='medical_processing.medicalreport')),
            ],
            options={
                'unique_together': {('report', 'allergen')},
            },
        ),
    ]
