# Generated by Django 4.2.10 on 2026-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='country',
            field=models.CharField(blank=True, help_text="User's country for regional food recommendations", max_length=100, null=True),
        ),
    ]
