# Generated by Django 4.2.10 on 2026-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userhealthprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
